### PR TITLE
Init django project with Docker & docker-compose

### LINKED ISSUE #2: Init Django project

### LINKED ISSUE #4: Docker & docker-compose
Create docker container and orchestration tool for running container applications

### PR DESCRIPTION
**Pull request by mjavorka**
Closes #2   
Closes #4

### CODE REVIEW

**Comment by zarybnicky** [comment]
Needs better naming: `RA-MPR/mpr/mpr/mpr/urls.py`? At least `backend` or `server`, please, we'll have the frontend here as well. Otherwise looks fine. @mjavorka

**Comment by zarybnicky** [comment]
Also, please don't remove the LICENSE file.

**Comment by mjavorka** [comment]
> Needs better naming: `RA-MPR/mpr/mpr/mpr/urls.py`? At least `backend` or `server`, please, we'll have the frontend here as well. Otherwise looks fine. @mjavorka

Thank you, you have a good point 👍 . I renamed the django project from `mpr` to `backend`

**Comment by mjavorka** [comment]
> Also, please don't remove the LICENSE file.

License file is back in the repository 🙂

**Comment by zarybnicky** [comment]
Thanks, looking good

**Pull request merged**
